name: Twitter to Discord News

on:
  schedule:
    # Runs at 10:00 AM UTC on Monday, Wednesday, and Friday
    # You can adjust the cron schedule to your desired days and times.
    # For example, '0 10 * * 1,3,5' means 10:00 AM UTC on Mon, Wed, Fri.
    # Learn more about cron syntax here: https://crontab.guru/
    - cron: '0 17 * * 1,3,5,6'
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  run-twitter-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Twitter to Discord Script
      env:
        # It's crucial to store sensitive information like your Bearer Token
        # as a GitHub Secret. Replace 'TWITTER_BEARER_TOKEN' with the
        # actual name of your secret.
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python main.py
